#!/usr/bin/ansible-playbook
---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: print out the hostname of target
    command: hostname

  - name: who is this
    command: whoami
